# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "npm"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Europe/Berlin"

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    open-pull-requests-limit: 10

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "npm (base)"

    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Europe/Berlin"

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    open-pull-requests-limit: 10

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions"

    rebase-strategy: "auto"
